name: Package Pure Node Docker Image

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Base Node Image
        run: |
          docker pull docker.io/library/node:18-alpine

      - name: Save Image to TAR
        run: |
          docker save -o node_base_image.tar docker.io/library/node:18-alpine

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-alpine-docker-image
          path: node_base_image.tar
          retention-days: 3
